find_package(KF6 COMPONENTS ConfigWidgets)

if(KF6_FOUND)
    set(QT_MIN_VERSION "6.4.0")
    set(QT_MAJOR_VERSION 6)
    set(KF_MIN_VERSION 6)
else(KF6_FOUND)
    set(QT_MIN_VERSION "5.15")
    set(QT_MAJOR_VERSION 5)
    set(KF_MIN_VERSION "5.78")
endif (KF6_FOUND)
