name: Kubuntu 22.04 Backports

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.png' ]
  pull_request:
    branches: [ master ]
    paths: [ '**/kubuntu2204-backports.yml' ]
  workflow_dispatch:
  schedule:
      - cron: "0 0 * * *"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DEB_NAME: kwin4_effect_shapecorners

jobs:
  kubuntu2204:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Refresh Ubuntu Packages
      run: sudo apt update

    - name: Add PPA support
      run: sudo apt install -y --no-install-recommends software-properties-common gpg-agent aptitude

    - name: Add Kubuntu Backports PPA
      run: sudo add-apt-repository -y ppa:kubuntu-ppa/backports-extra

    - name: Install Dependencies
      run: sudo aptitude install -y --without-recommends gettext extra-cmake-modules qttools5-dev libkf5configwidgets-dev kwin-dev
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build . --config ${{env.BUILD_TYPE}} -j

    - name: Package
      run: |
        cpack -V -G DEB
        DEB_FILE=artifacts/${DEB_NAME}_${GITHUB_JOB}.deb
        mkdir artifacts
        mv ${DEB_NAME}.deb ${DEB_FILE}
        echo "DEB_FILE=${DEB_FILE}" >> $GITHUB_ENV

    - name: Upload Workflow Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: ${{ env.DEB_NAME }}
        path: ${{ env.DEB_FILE }}
        compression-level: 0
        if-no-files-found: error

    - name: Upload to SourceForge
      if: github.ref == 'refs/heads/master'
      uses: nicklasfrahm/scp-action@main
      with:
        direction: upload
        host: ${{ secrets.SOURCEFORGE_HOST }}
        username: ${{ secrets.SOURCEFORGE_USERNAME }}
        key: ${{ secrets.SOURCEFORGE_KEY }}
        fingerprint: ${{ secrets.SOURCEFORGE_HOST_FINGERPRINT }}
        source: ${{ env.DEB_FILE }}
        target: /home/frs/project/kde-rounded-corners/nightly/kubuntu2204/${{ env.DEB_NAME }}_${{ github.job }}.deb
